# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2712362f1ac4794d2352aac0b4ef86195c38231c7bc6493b3754cfc290295423a4a1343571656baf72b64be38f862b3b6bdbccf19e3725ae8a8a70ff3ddddde1

test:
  secret_key_base: 2a6d48ce8a0219b29924a8ac4460641f9fe749bc99c2637a5e032bdce1d11f38b531dd0f0724330a8219fc0755d839acdd9cf306f26eb4bd5e434f427d0ae242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
